// <auto-generated />
using System;
using MEMCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MEMCore.Data.Migrations
{
    [DbContext(typeof(ExpenseContext))]
    [Migration("20190628063252_added_morecategryTypes")]
    partial class added_morecategryTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MEMCore.Domain.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExpenseCategoryId");

                    b.Property<DateTime>("ExpenseDate");

                    b.Property<string>("ExpenseTitle")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("ExpensesAmount");

                    b.Property<DateTime>("inDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("updateDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("MEMCore.Domain.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "grocery"
                        },
                        new
                        {
                            Id = 2,
                            Category = "restaurants"
                        },
                        new
                        {
                            Id = 3,
                            Category = "transportation"
                        },
                        new
                        {
                            Id = 4,
                            Category = "gifts"
                        },
                        new
                        {
                            Id = 5,
                            Category = "medical"
                        },
                        new
                        {
                            Id = 6,
                            Category = "insurance"
                        },
                        new
                        {
                            Id = 7,
                            Category = "clothing"
                        },
                        new
                        {
                            Id = 8,
                            Category = "education"
                        },
                        new
                        {
                            Id = 9,
                            Category = "utilities"
                        },
                        new
                        {
                            Id = 10,
                            Category = "shelter"
                        },
                        new
                        {
                            Id = 11,
                            Category = "personal"
                        },
                        new
                        {
                            Id = 12,
                            Category = "kids schooling"
                        },
                        new
                        {
                            Id = 13,
                            Category = "household items"
                        },
                        new
                        {
                            Id = 14,
                            Category = "fun money"
                        },
                        new
                        {
                            Id = 15,
                            Category = "office exp"
                        },
                        new
                        {
                            Id = 16,
                            Category = "personal"
                        },
                        new
                        {
                            Id = 17,
                            Category = "miscellaneous"
                        });
                });

            modelBuilder.Entity("MEMCore.Domain.ExpenseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Detail")
                        .HasMaxLength(250);

                    b.Property<int>("ExpenseId");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId")
                        .IsUnique();

                    b.ToTable("ExpenseDetail");
                });

            modelBuilder.Entity("MEMCore.Domain.Expense", b =>
                {
                    b.HasOne("MEMCore.Domain.ExpenseCategory", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MEMCore.Domain.ExpenseDetail", b =>
                {
                    b.HasOne("MEMCore.Domain.Expense", "Expense")
                        .WithOne("ExpenseDetail")
                        .HasForeignKey("MEMCore.Domain.ExpenseDetail", "ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
