// <auto-generated />
using MEMCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MEMCore.Data.Migrations
{
    [DbContext(typeof(ExpenseContext))]
    [Migration("20190626061439_Starter")]
    partial class Starter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MEMCore.Domain.Expense", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExpenseTitle")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("ExpensesAmount");

                    b.Property<string>("ExpensesDetails")
                        .HasMaxLength(250);

                    b.HasKey("id");

                    b.ToTable("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
